format = """
$sudo\
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$cmd_duration\
$line_break\
$python\
$character"""

#629477 - light greek
#d5fdd8 - white with the blue/greenish hue
#8ab1c2 - light blue
#ebaa4e - yellow with slight orange
#e48737 - orange
#db6d3c - peach
#d14432 - red orange
#267191 - dark blue

[sudo]
disabled = false
format = '[$symbol]($style)'

[username]
show_always = true
format = '[$user]($style)@'
style_user = "#db6d3c"

[hostname]
ssh_only = false
format = '[$hostname]($style) '
style = "#e48737" # orange

[directory]
style = "#8ab1c2" # light blue

[character]
success_symbol = "[❯](green)"
error_symbol = "[❯](red)"
vimcmd_symbol = "[❮](purple)"


[git_branch]
format = "[$branch]($style)"
style = "#629477" # light green

[git_status]
format = "[[(*$conflicted$untracked$modified$staged$renamed$deleted)](218) ($ahead_behind$stashed)]($style)"
style = "#629477" # light green
conflicted = "​"
untracked = "​"
modified = "​"
staged = "​"
renamed = "​"
deleted = "​"
stashed = "≡"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "#629477" # light green

[cmd_duration]
format = "[$duration]($style) "
style = "#ebaa4e" # yellowish

[python]
format = "[$virtualenv]($style) "
style = "#ebaa4e" # yellowish
